name: Run 3&D Scraper Weekly

on:
  workflow_dispatch:  # ręczne uruchomienie
  schedule:
    - cron: '0 9 * * 1'  # cron w poniedziałek
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests lxml beautifulsoup4

      - name: Run scraper
        run: python scraper_3d.py

      - name: Save CSV
        uses: actions/upload-artifact@v4
        with:
          name: 3d-players-weekly
          path: realgm_3d_players_weekly.csv
